<?php

require "Algoritimo.php";

class Fcfs extends Algoritimo
{
    public function __construct($processes)
    {
        $this->processes = $processes;

        $espera = 0;

        foreach ($this->processes as $k => $process){

            $process->espera_tempo = $espera;
            $this->processes[$k] = $process;

            $espera += $process->unidade_tempo;
        }
    }

    public function execute()
    {
        parent::execute(); // TODO: Change the autogenerated stub
        echo "RESULTADO\n";

        foreach ($this->processes as $process) {

            $this->espera_total += $process->espera_tempo;

            $p = $process->id +1;

            echo  "------------------------\n";
            echo "ID : p$p EXECUÇÃO : $process->unidade_tempo ESPERA : $process->espera_tempo  \n";
        }

        $soma_tempo = 0;
        foreach ($this->processes as $process) {
            for ($i = 0; $i < $process->unidade_tempo; $i++) {
                echo "\n";
                echo str_pad($this->tempo, 3, "0", 0) .": p" . ($process->id + 1);
                $this->tempo++;

            }
        }
        echo "\n\nMédia Espera: " . $this->espera_total/count($this->processes) ."\n";
    }
}